name: "Run with Output"
description: "Run with Output Action"

inputs:
  run:
    description: "Command to run"
    required: true

  cwd:
    description: "Working directory"
    required: false
    default: "."

outputs:
  stdout:
    description: "Standard output of the command"
    value: ${{ steps.run.outputs.stdout }}

  stderr:
    description: "Standard error of the command"
    value: ${{ steps.run.outputs.stderr }}

  exit_code:
    description: "Exit code of the command"
    value: ${{ steps.run.outputs.exit_code }}

runs:
  using: "composite"
  steps:
    - name: Run
      working-directory: ${{ inputs.cwd }}
      id: run
      shell: bash
      run: |
        # Run the command
        COMMAND='${{ inputs.run }}' ${{ github.action_path }}/src/main.sh #

branding:
  icon: "terminal"
  color: "gray-dark"
