name: "Run with Output"
description: "Run with Output Action"

inputs:
  run:
    description: "Command to run"
    required: true

outputs:
  stdout:
    description: "Standard output of the command"
    value: ${{ steps.run.outputs.stdout }}

  stderr:
    description: "Standard error of the command"
    value: ${{ steps.run.outputs.stderr }}

  exit_code:
    description: "Exit code of the command"
    value: ${{ steps.run.outputs.exit_code }}

runs:
  using: "composite"
  steps:
    - name: Run
      id: run
      shell: bash
      run: |
        # Run the command
        ${{ github.action_path }}/src/main.sh
      env:
        COMMAND: ${{ inputs.run }}

branding:
  icon: "terminal"
  color: "gray-dark"
