name: "Run with Output"
description: "Run with Output Action"

inputs:
  run:
    description: "Command to run"
    required: true

outputs:
  stdout:
    description: "Standard output of the command"
    value: ${{ steps.run.outputs.stdout }}

  stderr:
    description: "Standard error of the command"
    value: ${{ steps.run.outputs.stderr }}

runs:
  using: "composite"
  steps:
    - name: Run
      id: run
      shell: bash
      run: |
        {
          IFS=$'\n' read -r -d '' CAPTURED_STDOUT;
          IFS=$'\n' read -r -d '' CAPTURED_STDERR;
        } < <((printf '\0%s\0' "$(({
        ${{ inputs.run }}
        } | tr -d '\0') 3>&1- 1>&2- 2>&3- | tr -d '\0')" 1>&2) 2>&1)

        echo "stdout:"
        echo "$CAPTURED_STDOUT"
        {
          echo "stdout<<EOF"
          echo "$CAPTURED_STDOUT"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        echo "stderr:"
        echo "$CAPTURED_STDERR"
        {
          echo "stderr<<EOF"
          echo "$CAPTURED_STDERR"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

branding:
  icon: "terminal"
  color: "gray-dark"
