version: 3

silent: true

vars:
  NENV: "node_modules"

tasks:
  _prettier:
    internal: true
    cmds:
      - "{{.NENV}}/.bin/prettier {{.COMMAND}}"

  _with_nvm:
    internal: true
    cmds:
      - "source ${HOME}/.nvm/nvm.sh && nvm install && {{.COMMAND}}"

  init:
    desc: Initialize project environment
    cmds:
      - echo 'Installing node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm install" }

      - echo 'Installing husky pre-commit...'
      - task: _with_nvm
        vars: { COMMAND: "npm run prepare" }

  lint:
    desc: Lint project
    cmds:
      - task: _with_nvm
        vars: { COMMAND: "npm run lint:check" }

      - echo 'Running GHA checks...'
      - GH_TOKEN="$(gh auth token)" zizmor .

  lint-fix:
    desc: Lint fix project
    cmds:
      - task: _with_nvm
        vars: { COMMAND: "npm run lint:fix" }

      - echo 'Running GHA checks...'
      - GH_TOKEN="$(gh auth token)" zizmor .

  clean:
    desc: Clean project environment
    cmds:
      - echo 'Cleaning node dependencies...'
      - rm -rf {{.NENV}}

  dependencies-update:
    desc: Update dependencies
    cmds:
      - echo 'Updating node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm update" }

  dependencies-check:
    desc: Check dependencies
    cmds:
      - echo 'Checking node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm outdated" }
      - task: _with_nvm
        vars: { COMMAND: "npm audit" }

  update-from-template:
    desc: Update project from template
    cmds:
      - echo 'Updating project from template...'
      - cookiecutter
        --no-input
        --overwrite-if-exists
        --output-dir ../
        {{.TEMPLATE_PATH}}
        project_name='Run with Output Action'
        project_slug='run-with-output-action'
        marketplace_name='Run with Output'
        action_type='composite'
        node_version='v20.15.1'
        owner_name='Dmitry Ovsiannikov'
        owner_github_login='ovsds'
        with_zizmor='true'
    vars:
      TEMPLATE_PATH: '{{.TEMPLATE_PATH | default "https://github.com/ovsds/template-repository-github-action"}}'
