name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  e2e-stdout:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./
        with:
          run: |
            echo "test"
            echo "test2"

      - name: Assert stdout
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test.outputs.stdout }}
          expected: |
            test
            test2

  e2e-stderr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./
        with:
          run: |
            echo "test" 1>&2
            echo "test2" 1>&2

      - name: Assert stderr
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test.outputs.stderr }}
          expected: |
            test
            test2

  e2e-error-code:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./
        with:
          run: exit 1

      - name: Assert exit code
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test.outputs.exit_code }}
          expected: 1

  e2e:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - e2e-stdout
      - e2e-stderr
      - e2e-error-code

    steps:
      - name: Collect Results
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ toJson(needs) }}
          skip_allowed: false
