name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  e2e-default:
    runs-on: ubuntu-20.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test STDOUT
        id: test-stdout
        uses: ovsds/run-with-output-action@${{ github.ref_name  }}
        with:
          run: |
            echo "test"
            echo "test2"

      - name: Assert stdout
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-stdout.outputs.stdout }}
          expected: |
            test
            test2

      - name: Test STDERR
        id: test-stderr
        uses: ./
        with:
          run: |
            echo "test" 1>&2
            echo "test2" 1>&2

      - name: Assert stderr
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-stderr.outputs.stderr }}
          expected: |
            test
            test2
